### ISSUE TITLE
multiple accounts ?

### ISSUE THREAD

**Issue by mrphuong186** [MRColorR/money4band#101]
1. Nodepay and honeygain only allow 10 devices for 1 account, how to run more than 1 account? for example 40 proxies for 4 different accounts?

2. how to update new proxy? in V3 there is Setup and Management feature (multiple proxy versions by list)
just change proxy, it will update automatically in V4, I can't find

thanks a lot
![screenshot_1731285879](https://github.com/user-attachments/assets/f582484f-c759-41c5-ae7f-68e7e24031a9)

**Comment by MRColorR** [comment]
Hello! Thanks for reaching out and for using the Money4Band open-source project.

To run multiple Money4Band instances, you would normally follow the setup and provide proxies. If you also want to use different settings for a certain number of M4B instances, you can clone Money4Band into separate folders and set up each one with different settings. You can then enable multiproxy for these and let them spawn their replicas as needed. This way, you’ll be able to configure each group of instances to run independently. Remember to respect the terms of service (ToS) for each app, though.

As for the multi-proxy feature in V4, it’s not only still there, but it has been enhanced and is now part of the main setup function. During setup, you’ll be prompted to indicate whether you'd like to use a proxy, and it will guide you through the setup and creation process for everything proxy-related; there’s no need to start and stop them separately anymore.

If you have further questions or need additional tips, feel free to join us on the Money4Band Discord Community, where our team and other users are available to help!

Thank you again for your support and for using Money4Band!

**Comment by mrphuong186** [comment]
> Greetings! Thank you for contacting us and for utilizing the Money4Band open-source project.
> 
> To run multiple Money4Band instances on the same device, the standard procedure involves following the setup process and providing proxies. If you require distinct configurations for a specific number of M4B instances, you may clone Money4Band into separate directories and configure each one with unique settings. Subsequently, you can activate multiproxy for these instances and allow them to generate replicas as necessary. This approach enables you to configure each group of instances to operate autonomously. However, it is crucial to respect the terms of service (ToS) for each application.
> 
> Regarding the multi-proxy feature in V4, it is still there and it has been enhanced and integrated into the primary setup function. During the setup process, you will be prompted to specify whether you wish to use ome or more proxies. The setup will then guide you through the configuration and creation process for all proxy-related aspects; there is no longer a need to initiate and terminate them separately.
> 
> Should you have any further inquiries or require additional guidance, feel free to join us on the Money4Band Discord Community. Our team and other users are readily available to provide assistance.
> 
> We sincerely appreciate your support and continued use of Money4Band.

maybe you don't understand me
1. is it possible to run more than 1 account in 1 Money4Band version?
2. proxy update function suppose proxy is broken, in V3 there is
V4 i can't find
please guide me
thanks for your support

**Comment by MRColorR** [comment]
1) You can set up each Money4Band instance and all its proxy sub-instances with the same configuration. If you want to have different configurations, manually edit them after the setup step before starting, or copy the Money4Band folder and set it up with different credentials.

2) Proxy setup and startup are included in the standard setup and standard startup. If you want to update existing instance proxies, you can edit each proxy in the various instance configs or follow these steps: stop the stack and change the proxies in the proxy file, then do the setup again (it will be faster as the other settings are already there and you can just confirm them), and they will be updated.

Feel free to reopen the issue if you find something not working in Money4Band, or reach us on Discord for tips and information not related to technical issues.
