### ISSUE TITLE
cannot start

### ISSUE THREAD

**Issue by robihut** [MRColorR/money4band#105]
i reinstalled many times but it failed
please guide how to fix it
it seems it doesn't work with multi-proxy
thanks a lot
![screenshot_1733627868](https://github.com/user-attachments/assets/bd73c697-0b58-488d-8b0b-7c39e65dafbd)

**Comment by MRColorR** [comment]
hello, 
so you have this issue only when enabling multiproxy ?

**Comment by MRColorR** [comment]
see my comment on #102 . It's not clear whether you're running Money4Band from the zipped release or from the git cloned source code. I'd like to know if the same behavior is caused by a PyInstaller error or if it also affects the source code runs. so please try running from source code and let me know. ty

**Comment by robihut** [comment]
> hello, so you have this issue only when enabling multiproxy ?

yes i have problem running proxy

**Comment by robihut** [comment]
> see my comment on #102 . It's not clear whether you're running Money4Band from the zipped release or from the git cloned source code. I'd like to know if the same behavior is caused by a PyInstaller error or if it also affects the source code runs. so please try running from source code and let me know. ty



> from the zipped release

i run from zipped release
i tried zipped release version lower than 4.3.7 which i used fine before
and it still has the same error

**Comment by MRColorR** [comment]
my testing setup for this issue , 
- using unzipped release m4b 4.4.1  
- **all apps enabled excluding proxylite** (not worth atm), **speedhare** (currenlty dead), **gradient** (issue with arch manifests while pulling), **proxyrack** ( similar gradient issue)
- no notifications (silent apps updates)
- no extra apps
- no proxy

**Comment by MRColorR** [comment]
m4b 4.5.3+ should address also this issue feel free to test
