### ISSUE TITLE
can you help me with this?

### ISSUE THREAD

**Issue by GeoXTen** [MRColorR/money4band#18]
error during connect: in the default daemon configuration on Windows, the docker client must be run with elevated privileges to connect: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/json?all=1&filters=%7B%22label%22%3A%7B%22com.docker.compose.project%3Dmoney4band_515674103%22%3Atrue%7D%7D": open //./pipe/docker_engine: The system cannot find the file specified.

**Comment by MRColorR** [comment]
Hello, could you run `docker run hello-world` in a terminal or powershell ? if not, this confirms that your error is docker related. 

- Verify that Docker Desktop is "running" state. If not, launch it: that will run the docker daemon after a couple of minutes.
- try reboot your machine and on next boot check if docker is running.
- try also to restart docker service using the GUI option "restart docker" or restarting the docker service inside windows services menu (run services.msc to open it)
- Ensure all the prerequisites to have Docker Desktop installed and running in your environment are fulfilled (WSL+update , Virtualization Platform) 

**(Note: remember to add the necessary information when opening an issue , there's a template)**

**Comment by GeoXTen** [comment]
running on powershell

**Comment by GeoXTen** [comment]
oh it fix it

**Comment by GeoXTen** [comment]
and how example proxies does?

**Comment by MRColorR** [comment]
Normally you can run money4band without proxy. Optionally you can configure it to use your preferred proxy. You can use proxy if you want to run multiple instances of money4band on a single machine, or on multiple devices on a single public IP address or if you want to hide your IP address.
