### ISSUE TITLE
Problem with Traffmonetizer on rapsberry

### ISSUE THREAD

**Issue by dorel14** [MRColorR/money4band#22]
**Describe the bug**

Traffmonetizer was not sharing anything on my rapsberry 

**Device (please complete the following information):**
 - Type:  Raspberry Pi 3 B+
 - OS details: Latest Raspbian
 - Platform: [amd64 (64bit)

 
 **Docker**
 - Docker Compose version: Docker Compose version v2.11.2
 - Docker version: Version:           20.10.19

**To Reproduce**
Just install with actual docker compose file on rapsberry , look at traffmonetizer stats not sharing anything 

**Expected behavior**
I expect all docker container share something 

**Additional context**

I solve it changing my docker compose file with traffmonetizer/cli:arm64v8 instead of traffmonetizer/cli:latest

Perhaps i may be cool adding a docker compose file for raspberry

**Comment by MRColorR** [comment]
Hello, thank to reaching out 🙂👋
During install, did you followed the instructions to add multi platform support on raspberry?

**Comment by MRColorR** [comment]
> **Describe the bug** A clear and concise description of what the bug is.
> 
> Traffmonetizer was not sharing anything on my rapsberry
> 
> **Device (please complete the following information):**
> 
> * Type:  Raspberry Pi 3 B+
> * OS details: Latest Raspbian
> * Platform: [amd64 (64bit)
> 
> **Docker**
> 
> * Docker Compose version: Docker Compose version v2.11.2
> * Docker version: Version:           20.10.19
> 
> **To Reproduce** Just install with actual docker compose file on rapsberry , look at traffmonetizer stats not sharing anything
> 
> **Expected behavior** I expect all docker container share something
> 
> **Additional context**
> 
> I solve it changing my docker compose file with traffmonetizer/cli:arm64v8 instead of traffmonetizer/cli:latest
> 
> Perhaps i may be cool adding a docker compose file for raspberry

UPDATE: after a fresh install on a new raspberry i can confirm this issue is now present also if emulation layer is installed. Your solution is valid so until taffmonetizer devs update their docker image and fix this or i manage to push a patch in this repo your solution should be used. 

Thank you very much @dorel14 you were right. 
I'll leave this issue open until a generic permanent solution is found by me, traffmonetizer devs or others.

**Comment by MRColorR** [comment]
A test pre-release with a possible permanent fix is now available, testing and feedback is welcome.
You can find it at the following link https://github.com/MRColorR/money4band/releases/tag/v.1.3-alpha
