### ISSUE TITLE
bitping and traffmonetizer are in a cycle of restarts

### ISSUE THREAD

**Issue by Besix2** [MRColorR/money4band#24]
**Describe the bug**
title

[...]

**Device (please complete the following information):**
 - Type: Raspberry pi 4
 - OS details: linux
 - Platform: arm
 - Version raspian(newest)
 
 **Docker**
 - Docker Compose version:  v2.14.1
 - Docker version: Docker Engine community 20.10.22

**To Reproduce**
1. install docker via script
2. add emulation layer
3. setup .env file
4. start stack
**Expected behavior**
They should works as intended

**Screenshots**
![image](https://user-images.githubusercontent.com/92743858/211392225-bc4dc015-2b60-4260-8475-490ef0bcd096.png)

**Comment by MRColorR** [comment]
hello
could you please send me here the logs of the two containers? use `sudo docker logs traffmonetizer` and same for bitping. just the lates few lines of each

**Comment by Besix2** [comment]
![Screenshot_20230110-071918_Termux](https://user-images.githubusercontent.com/92743858/211476562-209025b3-b59b-4b9f-809d-f81663d63a08.jpg)

![Screenshot_20230110-071952_Termux](https://user-images.githubusercontent.com/92743858/211476615-6b3f5bb8-a993-4e5c-b624-fbf47390844c.jpg)


Just two screenshots before I go to work. When I get home I get more details. The screenshots are from termux sah into the pi.

**Comment by MRColorR** [comment]
### Bitping login problem
Bitping can't detect your login details in the .data/.bitping/ . 
Did you start the automatic setup from a terminal in the project's root folder or manually configured the env and docker file? The automatic script should guide you in the complete project setup and start a bitping interactive container in which you could enter your bitping credentials.
Anyway, to fix the issue you can stop the existing bitping container `sudo docker stop bitping` or the entire stack and then re-run this step opening a terminal in the money4band's root folder and entering 
`sudo docker run --rm -it -v ${PWD}/.data/.bitping/:/root/.bitping bitping/bitping-node` after login confirmation you can CTRL-C the interactive container and restart the original one or the entire stack. 
### Traffmonetizer "failed to create coreclr" problem
This is a bug, the traffmonetizer image pulled is an x86_64 as the latest tag of this image on docker at the moment is not multiarch but target x86_64 only (like in other apps e.g. Honeygain). The emulation layer should work around this problem (as it does for other apps) but traffmonetizer's image still gives errors. As stated in #22 I'm working on a permanent solution, but for now the fastest fix is:

1. Open the docker-compose file and edit the traffmonetizer image line changing `traffmonetizer/cli:latest` to `traffmonetizer/cli:arm64v8` then save the changes
2. Restart the project stack using the script or by opening a terminal in the docker-compose.yaml same folder and running `docker compose up -d`

**Comment by Besix2** [comment]
For Bitping I configured It using the Script. I put my credentials and IT World. But anyways I try It when I get home

**Comment by Besix2** [comment]
![image](https://user-images.githubusercontent.com/92743858/211562891-a885469f-8228-4e56-aafe-54febe875ae3.png)

Bitping seems to ignore the emulation layer

**Comment by Besix2** [comment]
Traffmonetizer work around doesnt work

![image](https://user-images.githubusercontent.com/92743858/211563874-1dc50901-b17e-411c-849d-dee3c70975f4.png)

**Comment by MRColorR** [comment]
Both seems networking related errors. bitping is using the emulation layer correctly as it is running and logging in, the architecture mismatch warning is just a heads up. Then it encounters a connection error. 
Also traffmonetizer workaround is not visible in the second screenshot, connection to docker hub to check images arch could not be established and went on timeout.

**Comment by MRColorR** [comment]
A test pre-release with a possible permanent fix is now available, testing and feedback is welcome.
You can find it at the following link https://github.com/MRColorR/money4band/releases/tag/v.1.3-alpha

**Comment by Besix2** [comment]
![image](https://user-images.githubusercontent.com/92743858/211820463-26ebe9b2-e99c-4bc9-adbb-b04941896224.png)

The text doubles in the new release

**Comment by MRColorR** [comment]
Thank you very much for your report. It was very precise and allowed me to solve quickly. 
Is the text still duplicating or was that also fixed in the latest release?

**Comment by MRColorR** [comment]
Thank you. I'll check it on a new test environment, when i can 👍
