### ISSUE TITLE
Add proxyrack/pop 

### ISSUE THREAD

**Issue by dorel14** [MRColorR/money4band#35]
Hello
Is it possible to add this bandwith sharing ?

**Comment by MRColorR** [comment]
yes i'll publish an updated release today. Thank you for the headsup.

**Comment by MRColorR** [comment]
I just added initial support for proxyrack so now money4band supports it too and we are ready to run the proxyrack app within the project.

Please note that at the moment the proxyrack image is really new and their devs probably need some time to squash a couple of bugs (like the ECONNREFUSED or 405 erorrs that i see sometimes in the logs). Also note that they only support x86_64 architectures but thanks to the emulation layer and the money4band internal image finder I was able to get it to work on both my x86_64 PC and my arm64 raspberry pi4. For better support just wait for the proxyrack devs to improve their docker images and maybe add new tags for more architectures so we don't have to use emulation.

Feel free to reopen this issue if new details or problems come up.

**Comment by dorel14** [comment]
Thx i will try and come back if needed
