### ISSUE TITLE
Unable to launch app stack

### ISSUE THREAD

**Issue by FencingFanatic** [MRColorR/money4band#37]
I have set up the .env file via the guided set up but it won't launch the apps from the menu. I was trying to do this on v1.4.1 

I received the below: 
This menu item will launch all the apps using the configured .env file and the docker-compose.yaml file (Docker must be already installed and running)
Do you wish to proceed Y/N?  y
"Money4Band" is not a valid project name: it must contain only characters from [a-z0-9_-] and start with [a-z0-9]
All Apps started you can visit the web dashboard on http://localhost:8081/ . If not already done use the previously generated earnapp node URL to add your device in your earnapp dashboard. Check the README file for more details.
Now press enter to go back to the menu

**Comment by MRColorR** [comment]
Hello, 
Please let me know on which docker version are you running the project , as workaround for now just open the .env file and change the project name to lower case . Then start the stack

**Comment by FencingFanatic** [comment]
I'm running on a pi4 with Debian GNU/Linux 11 (bullseye) and running Docker version 23.0.2

**Comment by MRColorR** [comment]
let me know if the workaround was enough to resolve the issue

**Comment by FencingFanatic** [comment]
Yes, that was enough to get it going.
