### ISSUE TITLE
Add https://proxylite.ru/

### ISSUE THREAD

**Issue by dorel14** [MRColorR/money4band#39]
**Is your feature request related to a problem? Please describe.**
Hello , is it possible to add this , there is a docker available

**Comment by MRColorR** [comment]
hello, yes it will be in the next release. The app is undergoing a refactoring phase now and several new functions will appear soon :)

**Comment by AceBeaker2** [comment]
proxylite no longer works, the website is down

**Comment by MRColorR** [comment]
Do you know how many days it's been offline? Anyway I will monitor the situation: if they are still not operational within the next week, I will remove their application from money4band.
