### ISSUE TITLE
open it not at  all working i was running instances the whole day but get any bandwith or device in all my apps 

### ISSUE THREAD

**Issue by Nishok000123** [MRColorR/money4band#48]
**Describe the bug**

[...]

**Device (please complete the following information):**
 - Type: [e.g. PC Desktop / Server / Raspberry Pi 3 B+/ Laptop ]
 - OS details: [e.g. Linux Ubuntu  / Windows / Mac ]
 - Platform: [e.g.  i386 (32bit) / x86_64 or amd64 (64bit) / arm64 (64bit) ]
 - Version [e.g. Ubuntu 22.10 / Windows 11 /  macOS Ventura ]
 
 **Docker**
 - Docker Compose version: [use `docker compose version` to discover installed version]
 - Docker version: [use `docker version` to discover installed version, write here the docker server version, e.g. Docker Desktop 14.13.1]

**To Reproduce**
3. See error

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by MRColorR** [comment]
hi, on what OS are you running the project? please try to give me more info so i can help you better :)

**Comment by Nishok000123** [comment]
Windows

**Comment by MRColorR** [comment]
Ok, good news , the problem you are experiencing is temporary and is specific to the latest version released. It is being discussed here #46 and should be fixed with the new release that will be released over the weekend.  In the menatime you can follow the manual setup instructions in the wiki.

**Comment by MRColorR** [comment]
this issue has been fixed in the latest release
