### ISSUE TITLE
peer2profit, image down

### ISSUE THREAD

**Issue by simon-bd** [MRColorR/money4band#56]
**Describe the bug**
When updating my Docker Compose file to pull the image `peer2profit/peer2profit_linux:latest`, I encountered the following error: "pull access denied for peer2profit/peer2profit_linux, repository does not exist or may require 'docker login': denied: requested access to the resource is denied."

**Device**
- Type: Intel NUC
- OS details: intel nuc
- Platform: x86_64 
- Version: Ubuntu 22.04.2 LTS (codename: jammy)

**Docker**
- Docker Compose version: Docker Compose version v2.16.0
- Docker version: 24.0.2

**To Reproduce**
1. Update Docker Compose file to include `peer2profit/peer2profit_linux:latest` image.
2. Run the Docker Compose command.
3. See the "pull access denied" error.

**Expected behavior**
I expected the Docker Compose command to successfully pull the `peer2profit/peer2profit_linux:latest` image without any errors.

**Screenshots**

**Additional context**
No additional context is provided at the moment.

**Comment by MRColorR** [comment]
hello simon-bd and thank you for letting us know. 
At first glance it appears that peer2profit has deleted their app image and removed their repo from dockerhub. we don't know at the moment if it's a temporary or permanent thing. Many users are now creating custom images of this single app (peer2profit) which are appearing on dockerhub, as many users now seem to create alternative images as a workaround. if you want to try one of these let us know the results of your discoveries: if a good alternative image is found it will be used as a substitute in the project.  If not, we will evaluate if it makes sense to make our own version of the peer2profit image

**Comment by simon-bd** [comment]
Currently chatting with them on telegram and they are saying that the image from them has been removed permanently

**Comment by simon-bd** [comment]
They just Said “Docker will not be supported anymore due to abusive usage.”

**Comment by MRColorR** [comment]
thanks for this update, we will evaluate how to proceed to keep peer2profit running in the project, we already have some options. For now if you have the last image from peer2profit (before their deletion) it still works fine and is still usable. 
Also, dave you tried any of the user cooked images posted on dockerhub for peer2profit?

**Comment by simon-bd** [comment]
I think they will stop supporting connections from containers. 

i tried a few of them and haven't gotten them to work :)

**Comment by dorel14** [comment]
Hello , 
After asking for support about this on telegram , they tell me that they will stop supporting connections from containers due to abuse

**Comment by MRColorR** [comment]
the old images seem to still work. 
**For those who don't have the old peer2profit image and can't download it**: I suggest you try to use one of the images created by the users present or skip peer2profit during the money4band setup. 
**Regarding the issue the team of peer2profit encountered**: a docker container is not that different from a linux pc so even if they don't support it anymore any problem they had with containers could happen even with the normal linux version. Also they can't differentiate and block them so easily. 

Summary to take away: For now you can use mone4band skipping the peer2profit setup or using a peer2profit user made image. As soon as a suitable image is found (let us know) or when we have time to create one, the issue will be closed.

**Comment by ni-73** [comment]
Any updates on peer2profit? The old image is not working, when copied to a different system, or when the container is restarted I get a message "software expired". Old images are working only in containers already running.

**Comment by MRColorR** [comment]
these additional info comes new to me , also now i see the peer2profit website is down , i'll monitor it

**Comment by MRColorR** [comment]
Using the new  .deb package to install the Linux version in a ubuntu container require GUI passtrough or connecting using vnc to login in peer2profit , I'll look for a possible workaround

**Comment by MRColorR** [comment]
has the peer2profit website is "down" too, the app has been moved to disabled apps until it works again .
Please download and try the new pre-release to test the newer apps and functions

**Comment by ni-73** [comment]
Website is down because they moved completely to telegram. From there you get all the information about payout, connected devices, referrals etc. App is working, they are just trying to limit somehow (I don't know why).

**Comment by MRColorR** [comment]
Thanks, now I understand better: they stopped supporting the web dashboard and docker images and switched to Telegram and continued to support their app only when installed directly on users' host systems.

What we will do:
- While waiting to find an already working image or a method to easily go through the GUI to configure the app (to create a usable image), the application will be moved within money4band into a separate list called "removed" apps. In reality the peer2profit application will still be present in money4band and it will be possible to carry out the manual setup as described in the wiki but for now it will not be managed by the automatic setup as at the moment only users who have already used peer2profit docker image in the past (as they have already logged in to the app) they can continue to use it as a containerized app.

- This allows us not to remove it completely, keeping it available for those who already have the app installed or for those who want to carry out tests and making it very simple to re-enable it for automatic setup in the future when a found solution is available.
- stack setup and launch will not remove the app if it is already present (it will be considered an orphaned container but will continue to work)
- Users who have already used money4band to set up the containerized version of peer2profit or who start using money4band  already having the peer2profit container will be able to continue running the containerized peer2profit app unless they remove the container or restart the stack using the remove-orphans flag.

These changes are already present in a feature branch that is now in testing, you can try it by switching to the extra-apps branch.

Also, if all goes well, a new stable version of money4band will be released within a couple of days. Thank you for your patience and your valuable feedback

**Comment by MRColorR** [comment]
i think i have found a viable workaround, it needs further testing

**Comment by MRColorR** [comment]
I published on docker hub a custom image for peer2profit, you can try it out and let me know if it works well for you too. 

If the feedback is good enough I'll add back peer2profit inside money4band guided setup script as an "extra app", it will require a little extra step from the users but it will be fully functional again.

Leave a star there too if you can thanks: https://hub.docker.com/r/mrcolorrain/peer2profit

**Comment by MRColorR** [comment]
This problem should be solved thanks to the new image that is now part of money4band.

**Comment by jenovauh** [comment]
Can I know if it is not working again? I try to use https://hub.docker.com/r/mrcolorrain/peer2profit. Using tinyVNC to connect to localhost:5901 and tinyvnc showing "Connection has been gracefully closed". Tried changing the ports and nothing seem to be able to connect.

**Comment by dorel14** [comment]
Hello ,  is there some news about this issue ?
