### ISSUE TITLE
proxylite.ru down

### ISSUE THREAD

**Issue by AceBeaker2** [MRColorR/money4band#58]
proxylite.ru is currently down and returns a 404 when queried

**Comment by MRColorR** [comment]
Thank you for letting me know  i'll check this during next week as I'm a bit overloaded right now. Their app had also some memory overflowing issue in the past  and they seemed to be in early stages of development. 
Until i can dig a little deeper inside this issue or their team can fix their bugs I recommend you to skip this app activation during money4band setup.
