### ISSUE TITLE
Add mystnodes https://mystnodes.com/

### ISSUE THREAD

**Issue by AceBeaker2** [MRColorR/money4band#61]
Just another bandwidth sharing service it would be cool to add

https://mystnodes.com/

**Comment by MRColorR** [comment]
Thank you, I  already know mysterium, for now it is not in money4band as its setup can't be fully automated and it is  bandwidth requiremets can affect user internet speed. 

I'm considering to add it and other more apps as "extra-apps" in money4band in the future if there's enough interest by the community

**Comment by MRColorR** [comment]
please download and try the new pre-release

**Comment by MRColorR** [comment]
This enhancement has been implemented in a feature branch and is now being tested, you can try switching to the extra-apps branch.

Also, if all goes well, a new stable version of money4band will be released within a couple of days. Thank you for your patience and your valuable feedback
