### ISSUE TITLE
Problem with CPU limit latest version

### ISSUE THREAD

**Issue by dorel14** [MRColorR/money4band#78]
**Describe the bug**
Hello 
I download the latest version ,  and i have this message when launchaing 5) start apps 

~~~
parsing /opt/money4band-2.7.5/docker-compose.yaml: error while interpolating services.earnapp.cpus: failed to cast to expected type: strconv.ParseFloat: parsing "1,2": invalid syntax
Error starting Docker stack. Please check the configuration and try again.
Now press enter to go back to the menu
~~~

**Device (please complete the following information):**
 - Type:  Raspberry Pi 3 B
 - OS details: Debian 12
 - Platform: arm64 (64bit) 
 - Version bullseye
 
 **Docker**
 - Docker Compose version: Docker Compose version v2.24.1
 - Docker version: 25.0.0

**To Reproduce**
1. Download latest 
2. Set up .env file with auto set up
3. Try to start apps

**Expected behavior**
I thought everything will start

For information when i test 
~~~
locale -k LC_NUMERIC
~~~

i got 
~~~
decimal_point=","
thousands_sep=" "
grouping=3
numeric-decimal-point-wc=44
numeric-thousands-sep-wc=8239
numeric-codeset="UTF-8"
~~~

**Comment by MRColorR** [comment]
Thank you, I'll look into it

**Comment by MRColorR** [comment]
yes the error message you're encountering (parsing "1,2": invalid syntax) suggests a locale issue as the script expects a dot (.) as the decimal separator, but the system locale is using a comma (,). 

Could you help me test a possible solution?: to enforce a consistent locale setting for number parsing set the LC_NUMERIC environment variable to C (which uses a dot as the decimal separator) at the start of the script after the shebang.
 so please try to edit the first lines of the script so it looks like this: 
 ```bash 
 #!/usr/bin/env bash
 export LC_NUMERIC="C"
 ```
 and report back if this solves your issue

**Comment by dorel14** [comment]
Hi , it seems to be OK , no more error message with this locale

**Comment by MRColorR** [comment]
Glad to hear that, the next release will contain this patch among other improvements.
