### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by jamalnggau1** [MRColorR/money4band#89]
Speedshare not work.. 
docker logs c99baabaa7c4
Using provided UUID: 95e5fba7eed6b2350605efd063bd9045
time="Jul 08 04:20:56" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 04:21:53" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 04:22:52" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 04:23:52" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 04:24:51" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 04:25:52" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 04:26:51" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 04:27:49" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 04:28:50" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 04:29:48" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 04:30:49" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 04:31:47" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 04:32:46" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 04:33:47" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 04:34:45" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 04:35:45" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 04:36:44" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 04:37:42" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 04:38:43" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 04:39:41" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 04:40:42" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 04:41:41" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 04:42:40" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 04:43:40" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 04:44:39" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 04:45:40" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
Using provided UUID: 95e5fba7eed6b2350605efd063bd9045
time="Jul 08 04:47:37" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 04:48:38" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 04:49:36" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 04:50:36" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 04:51:35" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 04:52:35" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 04:53:34" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 04:54:32" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 04:55:33" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 04:56:31" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 04:57:32" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 04:58:30" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 04:59:29" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 05:00:30" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 05:01:29" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 05:02:29" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 05:03:28" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 05:04:26" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 05:05:26" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 05:06:25" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 05:07:25" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 05:08:24" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 05:09:22" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 05:10:23" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 05:11:21" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 05:12:22" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 05:13:21" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 05:14:19" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 05:15:20" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 05:16:18" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 05:17:19" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 05:18:18" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 05:19:16" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 05:20:17" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 05:21:16" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 05:22:17" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 05:23:16" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 05:24:15" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 05:25:15" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 05:26:14" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 05:27:14" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 05:28:13" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 05:29:11" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 05:30:12" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 05:31:10" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 05:32:11" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 05:33:09" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 05:34:08" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 05:35:09" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 05:36:07" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 05:37:07" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 05:38:06" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 05:39:05" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 05:40:06" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 05:41:05" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 05:42:06" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 05:43:04" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 05:44:04" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 05:45:03" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 05:46:02" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 05:47:02" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 05:48:01" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 05:49:01" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 05:50:00" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 05:50:59" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 05:51:59" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 08 05:52:57" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
root@amlogic:~/money4band-main#

**Comment by MRColorR** [comment]
Speedshare server is down or their configuration has changed,  so please contact them and if you discover something needs to be updated on our image report back.

**Comment by MRColorR** [comment]
Thank you for your patience :) There are no issues on our end. We have contacted the developers at SpeedShare and are now awaiting their action to restore their server.  👍
