### ISSUE TITLE
I can’t able to run. 

### ISSUE THREAD

**Issue by MolnarMilan000** [MRColorR/money4band#92]
Error starting docker stack. 
![IMG_9409](https://github.com/user-attachments/assets/c1123d92-ccc4-4b3a-b426-d33d26d58ca4)
![IMG_9410](https://github.com/user-attachments/assets/4d0cc8c0-236b-4da6-9553-7cfaf1a935fe)

**Comment by MolnarMilan000** [comment]
I try to run on fedora vps

**Comment by MRColorR** [comment]
Hello , thank you for reaching out. Are you on money4band v3.x or on the money4band v4 beta branch? 

Also please tell us the info about docker version in use and if you've enabled multi-proxy or not.

As a workaround move to the money4band folder and launch the `docker compose up -d` command directly from the terminal.

**Comment by MRColorR** [comment]
We haven’t received any updates or responses on this issue for a while, so we’re going to close it for now. If you still need assistance or have more information to provide, please feel free to reopen the issue
