### ISSUE TITLE
Web Dashboard

### ISSUE THREAD

**Issue by mrphuong186** [MRColorR/money4band#96]
please guide how to open Web Dashboard in VM ubutu ?
thanks a lot

**Comment by MRColorR** [comment]
Hello and thank you for reaching out.

To reach the M4B Web Dashboard, follow these steps:

- **Accessing from the Same Machine Running M4B’s Dashboard Web Server**
If you are on the same machine where M4B’s dashboard is running, you can access the dashboard by navigating to localhost:PORT in your web browser. localhost is shorthand for the loopback internal interface IP, 127.0.0.1. So localhost:PORT is equivalent to 127.0.0.1:PORT.

- **Accessing from Another Device in the Same LAN**
If you are on a different device but within the same LAN as the M4B dashboard server, use the local IP address of the server followed by the port number, like 192.168.1.2:PORT. You can find the local IP address of the M4B server in the network settings or by using ipconfig (Windows) or ifconfig (Linux/Mac).

- **Accessing from Outside the LAN (Internet)**
For access from outside your LAN, you need to set up port forwarding on your router to direct external requests to the M4B server. Log in to your router’s admin interface and find Port Forwarding, Virtual Server, or NAT Forwarding. Set the internal IP of the M4B server, the port number, and the external port you wish to use. After setup, you can access the dashboard via your external IP address and the external port, like EXTERNAL_IP:EXTERNAL_PORT.

- **Accessing from a Remote Server**
If the M4B dashboard is running on a remote server, you have two options to access it:
   - Direct Access: Access the dashboard directly by navigating to the server’s external IP address followed by the M4B port, like EXTERNAL_IP:PORT.
    - SSH remote to local port forwarding: Use SSH remote to local port forwarding to expose the remote port to your local port. This allows you to access the dashboard by pointing to localhost:PORT on your local machine. 



For more info or questions refer to our Discord community inside the forum posts as this topic has been already discussed [there](https://discord.com/channels/1111443305893474388/1192461372919906315)

**Comment by mrphuong186** [comment]
thank you, i will try
i want to ask more, how to add a new project to the activity list ?
please guide
thank you very much

**Comment by MRColorR** [comment]
I'm not certain what you're referring to, but this matter does not pertain to a coding issue and should be addressed within the Money4Band Discord community or through GitHub discussions, rather than in an issue report. Please feel free to contact us through one of these more suitable channels for such inquiries.
